version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  jobs:
    install:
      - cargo install mdbook
      - cargo install mdbook-mermaid
    build:
      html:
        # For an example book..
        # - mdbook init docs
        - mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html