version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
    python: "3"
  jobs:
    build:
      html:
        - cargo install mdbook
        - cargo install mdbook-mermaid
        - asdf reshim rust
        - pip install git+https://github.com/tgolsson/python-apibook.git
        - python-apibook game/terminal docs/src --summary-template-file docs/SUMMARY.tmpl
        - mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html